name: ci

on:
  # we only expect to run when trigger externals with a tag
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump
        run:
          echo  '${{ toJSON(github.event.client_payload) }}'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: blaufuss/test-image:${{ github.event.client_payload.tag }}-${{ steps.date.outputs.date }}, blaufuss/test-image:${{ github.event.client_payload.tag }}-latest
